---
title: "XGBoost_Impute_Values_SubModel"
author: "Jerome Dixon"
date: "1/29/2021"
output:
  word_document: default
  html_document: default
---

```{r setup2, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readr)
library(tidyverse)
library(purrr)
library(dplyr)
library(magrittr)
library(formattable)
library(knitr)
library(lubridate)
library(xts) 
library(forecast) 
library(ggplot2) 
library(TTR)
library(data.table)
library(padr)
library(xgboost)
library(Matrix)
library(RcppRoll)
library(zoo)
library(xtable)


```

```{r}


trains <- read_csv("data/trains.csv")

trains %<>% select(2,3,4,5)


names(trains)[3] <- "Percent_Available"
names(trains)[4] <- "Average_Age_in_Years"

trains$`Percent_Available` <- na_if(trains$`Percent_Available`, "U")
trains$`Percent_Available` <- as.numeric(trains$`Percent_Available`)

# Remove NAs. Create Training Dataset
trains_complete_cases <- trains[complete.cases(trains), ]


```

```{r}


trains_complete_cases$Date <- as.integer(trains_complete_cases$Date)

trains_complete_cases$Train_Type <- as.factor(trains_complete_cases$Train_Type)



```


```{r}

MinDate <- min(trains_complete_cases$Date)

MaxDate <- max(trains_complete_cases$Date)

train <- subset(trains_complete_cases, Date < 2012)
test <- subset(trains_complete_cases, Date >= 2012)


```


```{r Test Matrix}


test_xgb <- test[order(test$Date),]

label_xgb <- test_xgb$Percent_Available

previous_na_action <- options('na.action')
options(na.action='na.pass')

train_Matrix <- sparse.model.matrix(~ Date + Train_Type + Average_Age_in_Years
                                   , data = test_xgb
                                   , contrasts.arg = NULL
                                   , sparse=FALSE, sci=FALSE)

options(na.action = previous_na_action)


XGB_Matrix <- xgb.DMatrix(data=train_Matrix, label = label_xgb)

```


```{r}

xgb_params  <- list(booster = "gbtree"
               , objective = "reg:squarederror"
               , eta=0.4
               , gamma=0
               )


```

```{r}

trains.xgb  <- xgb.cv(data = XGB_Matrix
                  , param = xgb_params
                  , maximize = FALSE, evaluation = "rmse", nrounds = 100
                  , nthreads = 10, nfold =2, early_stopping_rounds = 10)



```

```{r}

trains_iterations = trains.xgb$best_iteration

trains.model.xgb <- xgb.train(data = XGB_Matrix
                   , param = xgb_params
                   , maximize = FALSE, evaluation = "rmse", nrounds = trains_iterations)

trains.model.xgb


```


```{r}

feature.importance.trains <- xgb.importance(feature_names = colnames(XGB_Matrix), model = trains.model.xgb)
xgb.ggplot.importance(importance_matrix = feature.importance.trains, top_n = 5) +
  labs(title = "Top Features") +
  theme_minimal()

ggsave('images/trains-feature-importance.png')


```


```{r}

# Incomplete Cases
trains_incomplete_cases <- trains[!complete.cases(trains), ]

new_data <- trains_incomplete_cases[order(trains_incomplete_cases$Date),]

label_xgb <- trains_incomplete_cases$Percent_Available

previous_na_action <- options('na.action')
options(na.action='na.pass')

new_data_Matrix <- sparse.model.matrix(~ Date + Train_Type + Average_Age_in_Years
                                   , data = trains_incomplete_cases
                                   , contrasts.arg = NULL
                                   , sparse=FALSE, sci=FALSE)

options(na.action = previous_na_action)


new_data_DMatrix <- xgb.DMatrix(data=new_data_Matrix, label = label_xgb)

new_data_prediction <- predict(trains.model.xgb, newdata = new_data_DMatrix)


```


```{r}

trains_incomplete_cases$Percent_Available <- new_data_prediction

imputed_values <- trains_incomplete_cases

final_amtrak_data <- rbind(trains_complete_cases, imputed_values) %>% arrange(Date) 
is.num <- sapply(final_amtrak_data, is.numeric)
final_amtrak_data[is.num] <- lapply(final_amtrak_data[is.num], round, 1)


write.csv(final_amtrak_data, "data/Final_Amtrak_df.csv")

head(final_amtrak_data, 5)


```



